import { Poppins, Merienda } from "next/font/google";
import "./globals.css";
import "@/styles/main.scss";
import Header from "@/components/layouts/header";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "700", "500", "600", "800"],
});
const merienda = Merienda({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-merienda",
  weight: ["400", "700", "500", "600", "800"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
